---
# tasks file for sbaerlocher.update-management

- name: 'Set Update Managment Enable'
  set_fact:
    update_management_Windows_enable: false
  when: update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::ActiveHours
- name: Turn off auto-restart for updates during active hours
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable
  with_items:
    - {
        name: SetActiveHours,
        data: "{{ '00000001' if update_management_SetActiveHours_enabled else '00000000' }}",
      }
    - {
        name: ActiveHoursStart,
        data: '{{ update_management_ActiveHoursStart }}',
      }
    - { name: ActiveHoursEnd, data: '{{ update_management_ActiveHoursEnd }}' }

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::AutoUpdateCfg
- name: Configure Automatic Updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: "{{ '00000001' if update_management_NoAutoUpdate_enable else '00000000' }}"
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
    type: dword
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::AutoUpdateCfg
- name: Configure Automatic Updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: AUOptions
    data: '{{ update_management_AUOptions }}'
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
    type: dword
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::AutoUpdateCfg
- name: Configure Automatic Updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable
  with_items:
    - {
        name: ScheduledInstallDay,
        data: '{{ update_management_ScheduledInstallDay }}',
      }
    - {
        name: ScheduledInstallTime,
        data: '{{ update_management_ScheduledInstallTime }}',
      }
    - {
        name: ScheduledInstallEveryWeek,
        data: '{{ update_management_ScheduledInstallEveryWeek }}',
      }
    - {
        name: AllowMUUpdateService,
        data: '{{ update_management_AllowMUUpdateService }}',
      }

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::AutoRestartNotificationDisable
- name: Turn off auto-restart notifications for update installations
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: SetAutoRestartNotificationDisable
    data: '{{ update_management_SetAutoRestartNotificationDisable }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::IncludeRecommendedUpdates_Title
- name: Turn on recommended updates via Automatic Updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: IncludeRecommendedUpdates
    data: '{{ update_management_IncludeRecommendedUpdates }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::AutoRestartDeadline
- name: Specify deadline before auto-restart for update installation
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable
  with_items:
    - {
        name: AutoRestartDeadlinePeriodInDays,
        data: '{{ update_management_AutoRestartDeadlinePeriodInDays }}',
      }
    - {
        name: SetAutoRestartDeadline,
        data: '{{ update_management_SetAutoRestartDeadline }}',
      }

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::DetectionFrequency_Title
- name: Automatic Updates detection frequency
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable
  with_items:
    - {
        name: DetectionFrequencyEnabled,
        data: '{{ update_management_DetectionFrequencyEnabled }}',
      }
    - {
        name: DetectionFrequency,
        data: '{{ update_management_DetectionFrequency }}',
      }

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::EngagedRestartTransitionSchedule
- name: Specify Engaged restart transition and notification schedule for updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable
  with_items:
    - {
        name: SetEngagedRestartTransitionSchedule,
        data: '{{ update_management_SetEngagedRestartTransitionSchedule }}',
      }
    - {
        name: EngagedRestartTransitionSchedule,
        data: '{{ update_management_EngagedRestartTransitionSchedule }}',
      }
    - {
        name: EngagedRestartSnoozeSchedule,
        data: '{{ update_management_EngagedRestartSnoozeSchedule }}',
      }
    - {
        name: EngagedRestartDeadline,
        data: '{{ update_management_EngagedRestartDeadline }}',
      }

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::DisableUXWUAccess
- name: Remove access to use all Windows Update features
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: SetDisableUXWUAccess
    data: '{{ update_management_SetDisableUXWUAccess }}'
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
    type: dword
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::ExcludeWUDriversInQualityUpdate
- name: Do not include drivers with Windows Updates
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: ExcludeWUDriversInQualityUpdate
    data: "{{ '00000001' if update_management_Noincludedrivers_enable else '00000000' }}"
    state: "{{ 'present' if update_management_Noincludedrivers_enable else 'absent' }}"
    type: dword
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::DeferFeatureUpdates
- name: Select when Preview Builds and Feature Updates are received
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: '{{ item.type }}'
    state: "{{ 'present' if update_management_Windows_enable else 'absent' }}"
  when: not update_management_GPO_enable
  with_items:
    - {
        name: DeferFeatureUpdates,
        type: dword,
        data: '{{ update_management_DeferFeatureUpdates }}',
      }
    - {
        name: BranchReadinessLevel,
        type: dword,
        data: '{{ update_management_BranchReadinessLevel }}',
      }
    - {
        name: DeferFeatureUpdatesPeriodInDays,
        type: dword,
        data: '{{ update_management_DeferFeatureUpdatesPeriodInDays }}',
      }
    - {
        name: PauseFeatureUpdatesStartTime,
        type: String,
        data: '{{ update_management_PauseFeatureUpdatesStartTime }}',
      }

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::CorpWuURL
- name: Use Windows Update Server
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: UseWUServer
    data: "{{ '00000001' if update_management_UseWUServer_enable else '00000000' }}"
    state: "{{ 'present' if update_management_UseWUServer_enable else 'absent' }}"
    type: dword
  when: not update_management_GPO_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::CorpWuURL
- name: Set the intranet update service for detecting updates
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: WUServer
    data: update_management_WUServer
    state: "{{ 'present' if update_management_WUServer else 'absent' }}"
    type: string
  when: not update_management_GPO_enable and update_management_UseWUServer_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::CorpWuURL
- name: Set the intranet statistics server
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: WUStatusServer
    data: update_management_WUStatusServer
    state: "{{ 'present' if update_management_WUStatusServer else 'absent' }}"
    type: string
  when: not update_management_GPO_enable and update_management_UseWUServer_enable

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::CorpWuURL
- name: Set the alternate download server
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: UpdateServiceUrlAlternate
    data: update_management_UpdateServiceUrlAlternate
    state: "{{ 'present' if update_management_UpdateServiceUrlAlternate else 'absent' }}"
    type: string
  when: not update_management_GPO_enable and update_management_UseWUServer_enable
